music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.index, name='index'),
    # /music/my-albums/
    url(r'^my-albums/$', views.my_albums, name='my-albums'),
    # /music/22/
    url(r'^(?P<album_id>[0-9]+)/$', views.details, name='details'),
    # /music/22/favorite/
    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),

]

project2/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from music import views as v

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url('^accounts/login/', views.LoginView.as_view(), name='login'),
    url('^accounts/logout/', views.LogoutView.as_view(next_page='/music/'), name='logout'),
    url(r'^signup/$', v.signup, name='signup'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Album(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='albums', default=1, null=True)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    favourite_songs = models.ManyToManyField(Song, related_name='profiles', blank=True)
    profile_photo = models.FileField(blank=True)
    bio = models.CharField(max_length=20, default="")


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

music/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    # profile_photo = forms.FileField()
    bio = forms.CharField(max_length=20)
    email = forms.EmailField(max_length=25)

    class Meta:
        model = User
        fields = ('username', 'email', 'bio', 'password1', 'password2')

music/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from .models import Album, Song
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm
from django.contrib.auth import login, authenticate


def index(request):
    all_albums = Album.objects.all()
    return render(request, 'music/index.html', {'all_albums': all_albums})


def my_albums(request):
    user = request.user
    albums = user.albums.all()
    return render(request, 'music/myalbums.html', {'albums': albums})


@login_required
def details(request, album_id):
    # album = get_object_or_404(Album, pk=album_id)
    try:
        album = Album.objects.get(pk=album_id)
    except Album.DoesNotExist:
        raise Http404('Album does not exist')
    return render(request, 'music/details.html', {'album': album})


@login_required
def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/details.html', {'album': album,
                                                      'error_message': "you did not select a valid song"})
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/details.html', {'album': album})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.profile.bio = form.cleaned_data.get('bio')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('/music/')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

music/templates/music/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
<link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Marck+Script" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
<link rel="stylesheet" href="{% static 'css/music.css' %}">
    <title>Musico</title>

<style>
    {% block style %}
    {% endblock %}
</style>
</head>
<body>

<div class="backg">
<ul>
    <li><a style="font-family:'Marck Script', cursive;font-style: italic; font-size: 18px" href="{% url 'music:index' %}">Musico</a></li>
    {% block active %}
        <li><a href="{% url 'music:index' %}" class="active"><i class='fas fa-headphones active' style='font-size:16px'></i> Albums</a></li>
        <li><a href=""><i class='fas fa-music' style='font-size:16px'></i> Songs</a></li>
    {% endblock %}
    {% if user.is_authenticated %}
        <li style="float:right"><a href="{% url 'logout' %}"><i class='fa fa-sign-out' style='font-size:16px'></i> Logout</a></li>
        <li style="float:right"><a href="">Hello {{ user.username }}</a></li>
    {% else %}
        <li style="float:right"><a href="{% url 'login' %}">Login</a></li>
        <li style="float:right"><a href="{% url 'signup' %}">Signup</a></li>
    {% endif %}
</ul>

     {% block content %}
     {% endblock %}
</div>
</body>
</html>

music/templates/music/details.html
{% extends 'music/base.html' %}
{% block style %}
  h1, h2, img, form {margin-left: 30px}
{% endblock %}

{% block active %}
    <li><a href="{% url 'music:index' %}"><i class='fas fa-headphones' style='font-size:16px'></i> Albums</a></li>
  <li><a href="" class="active"><i class='fas fa-music active' style='font-size:16px'></i> Songs</a></li>
{% endblock %}

{% block content %}
    <h1>{{ album.album_title }}</h1>
    <h2>{{ album.artist }}</h2>
    <img src="{{ album.album_logo.url }}" alt="logo" width="300px">
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'music:favorite' album.id %}" method="post">
        {% csrf_token %}
        {% for song in album.song_set.all %}
            <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
            <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="http://i.imgur.com/b9b13Rd.png" />
            {% endif %}
            </label><br>
        {% endfor %}
        <input type="submit" value="Favorite">
    </form>

{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block style %}
{% endblock %}


{% block content %}

{% if all_albums %}

<div class="flex-container">
     {% for album in all_albums %}
      <div class="album">
      <img src="{{ album.album_logo.url }}" alt="logo" style="width:100%"><br>
      <a href="{% url 'music:details' album.id %}">{{ album.album_title }}</a>
      <br>
      <button href="{% url 'music:details' album.id %}" class="button button2">Details</button>
      <a class="icon" href=""><i class="fa fa-trash-o" style="font-size:18px"></i></a>
      <a class="icon" href=""><i class="fa fa-heart-o" style="font-size:18px; color: #999999"></i></a>
      </div>
     {% endfor %}
</div>

{% else %}
  <h3>don't have any album</h3>
{% endif %}

{% endblock %}

music/templates/music/myalbums.html
{% extends 'music/base.html' %}

{% block style %}
{% endblock %}


{% block content %}

{% if albums %}

<div class="flex-container">
     {% for album in albums %}
      <div class="album">
      <img src="{{ album.album_logo.url }}" alt="logo" style="width:100%"><br>
      <a href="{% url 'music:details' album.id %}">{{ album.album_title }}</a>
      <br>
      <button href="{% url 'music:details' album.id %}" class="button button2">Details</button>
      <a class="icon" href=""><i class="fa fa-trash-o" style="font-size:18px"></i></a>
      <a class="icon" href=""><i class="fa fa-heart-o" style="font-size:18px; color: #999999"></i></a>
      </div>
     {% endfor %}
</div>

{% else %}
  <h3>don't have any album</h3>
{% endif %}

{% endblock %}